# Generated by Django 6.0.4 on 2026-05-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
